<?php
	require('rich-text.php');
	require('image-columns.php');
	require('one-image.php');
	require('text-box.php');
	require('social-media.php');
	require('columns-image-text-box.php');
	require('image-sizes.php');
	require('product.php');
?>